import ServiceCarousel3D from './ServiceCarousel3D';
import Chatbot from './Chatbot';
import FloatingPillNavigation from './FloatingPillNavigation';
import PortfolioSkeleton from './PortfolioSkeleton';
import simplabotsImage from '../images/simplabots-preview.jpg';
import marciImage from '../images/marci-metzger-preview.jpg';
import chatbotImage from '../images/ai-chatbot.png';
import complianceImage from '../images/phcompliance-preview.jpg';
import mangoImage from '../images/carabao-mango.jpg';
import profileImage from '../images/profile.jpg';

const projects = [
  { title: 'SimplaBots Platform', category: 'AI Platform · Next.js', description: 'Agentic AI assistants for businesses with whitelabel configuration, analytics, and multi-model integrations.', tags: ['Next.js', 'TypeScript', 'PostgreSQL', 'OpenAI'], image: simplabotsImage, year: '2025', liveUrl: 'https://simplabots.com/' },
  { title: 'Marci Metzger Website', category: 'Web Experience', description: 'An elegant single-page redesign built around responsive rhythm, smooth animation, and professional typography.', tags: ['HTML', 'CSS', 'JavaScript'], image: marciImage, year: '2025', liveUrl: 'https://magenta-stroopwafel-2e14c2.netlify.app/' },
  { title: 'AI Chatbot with Gemini', category: 'Applied AI · Python', description: 'A Streamlit assistant with Gemini integration, authentication, and persistent chat history management.', tags: ['Python', 'Streamlit', 'Firebase', 'Gemini'], image: chatbotImage, year: '2025', liveUrl: 'https://ai-chatbot-vkuzpra8bb6qgbqdyseutu.streamlit.app/' },
  { title: 'Compliance Website', category: 'Product Interface', description: 'A regulatory management application designed to make organizational standards easier to track and act on.', tags: ['React', 'Node.js', 'Database'], image: complianceImage, year: '2025', liveUrl: 'https://phcompliance.netlify.app/' },
  { title: 'Carabao Mango Sensor', category: 'IoT · Data Systems', description: 'An environmental monitoring system for mango cultivation with real-time visualization and analytics.', tags: ['IoT', 'Dashboard', 'Real-time Analytics'], image: mangoImage, year: '2025', liveUrl: '/mango-dashboard.html' },
];

const skills = {
  Languages: ['JavaScript', 'TypeScript', 'Python', 'HTML', 'CSS'],
  'Web & Frontend': ['React', 'Next.js', 'Node.js', 'Tailwind CSS', 'Firebase'],
  'Databases & Backend': ['PostgreSQL', 'SQL', 'Non-SQL', 'Prisma ORM', 'Firebase'],
  'AI & Data Science': ['Streamlit', 'Data Science', 'RAG', 'LLM Fine-tuning', 'Pinecone'],
  'AI Integrations': ['OpenAI', 'Claude', 'Gemini', 'Vector Search'],
  'Tools & Platforms': ['Make', 'Flowise', 'n8n', 'Zapier', 'AWS', 'Cursor', 'Windsurf', 'Claude Code'],
};

const experiences = [
  { role: 'AI Software Developer', company: 'Outrank Strategy', period: 'April 2025 - Present', location: 'Centerville, UT · Remote', highlights: ['Developed SimplaBots, a suite of agentic AI assistants for businesses.', 'Built responsive interfaces with Next.js, TypeScript, and Tailwind CSS.', 'Implemented whitelabel configuration for branded AI agents.', 'Integrated OpenAI, Claude, Gemini, and Pinecone vector search.', 'Collaborated on real-time analytics powered by AWS SQS and SES.', 'Designed scalable front-end architecture for modular expansion.'], tech: ['Next.js', 'TypeScript', 'React', 'PostgreSQL', 'AWS', 'OpenAI API'], current: true },
  { role: 'Data Scientist (Company WideChatbot)', company: 'Connext - Internship', period: 'July 2024 - August 2024', location: 'Pampanga, Philippines · Remote', highlights: ['Architected and deployed a company-wide chatbot with Streamlit and Python.', 'Implemented RAG and fine-tuned LLMs for technical documentation accuracy.', 'Performed web scraping and data extraction from complex website structures.', 'Organized extracted data into clean, well-formatted datasets.'], tech: ['Python', 'Streamlit', 'RAG', 'LLM', 'Web Scraping'] },
];

const certifications = [['🏆', 'AI Hackathon 3rd Place', '2024'], ['⭐', 'Starknet Winter Hackathon Participant', '2024'], ['📚', 'Analysis and Algorithms', '2025'], ['🤖', 'Azure AI Foundry', 'Building AI Agents and Apps · 2025'], ['📜', 'Certificate of Attendance', '2024']];

export default function PortfolioApp() {
  return <PortfolioSkeleton images={[profileImage, ...projects.map((project) => project.image)]}>
    <FloatingPillNavigation />
    <section id="hero" className="hero"><div className="container"><div className="hero-content"><div className="hero-text"><span className="hero-subtitle">A workspace for intelligent things</span><h1 className="hero-title"><span className="text-highlight">Arone Christian V. Titong</span></h1><p className="hero-role">AI Software Developer</p><p className="hero-description">Explore AI products, interfaces, and experiments engineered by Arone Titong. Creating intelligent solutions with Next.js, Python, and React.</p><div className="hero-cta"><a href="#contact" className="btn btn-primary"><span>Get In Touch</span><span aria-hidden="true">→</span></a><a href="#projects" className="btn btn-secondary">View My Work</a></div><div className="hero-stats"><div className="stat"><span className="stat-value">5+</span><span className="stat-label">Projects</span></div><div className="stat"><span className="stat-value">2+</span><span className="stat-label">Years</span></div><div className="stat"><span className="stat-value">40+</span><span className="stat-label">Skills</span></div></div></div><div className="hero-image"><div className="image-wrapper"><img src={profileImage} alt="Arone Christian V. Titong" className="profile-photo" /><div className="image-badge">Available for work</div></div></div></div></div></section>
    <section id="projects" className="section"><div className="container"><h2 className="section-title">Featured Projects</h2><ServiceCarousel3D cards={projects} /></div></section>
    <section id="experience" className="section alt-bg"><div className="container"><h2 className="section-title">Work Experience</h2><div className="experience-timeline">{experiences.map((experience) => <article className={`experience-item${experience.current ? ' featured' : ''}`} key={experience.role}><div className="experience-badge">{experience.current ? 'Current' : 'Internship'}</div><div className="experience-header"><div><h3>{experience.role}</h3><p className="company">{experience.company}</p></div><span className="dates">{experience.period}</span></div><p className="location">{experience.location}</p><ul className="experience-list">{experience.highlights.map((highlight) => <li key={highlight}>{highlight}</li>)}</ul><div className="experience-tech">{experience.tech.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></div></section>
    <section id="skills" className="section alt-bg"><div className="container"><h2 className="section-title">Skills & Technologies</h2><div className="skills-grid">{Object.entries(skills).map(([category, items]) => <article className="skill-category" key={category}><h3>{category}</h3><div className="skill-tags">{items.map((item) => <span className="skill-tag" key={item}>{item}</span>)}</div></article>)}</div></div></section>
    <section id="about" className="section"><div className="container"><h2 className="section-title">About Me</h2><div className="about-grid"><article className="about-card"><div className="about-icon">🎯</div><h3>Mission</h3><p>Building intelligent, scalable solutions that solve real-world problems using AI and modern development practices.</p></article><article className="about-card"><div className="about-icon">💡</div><h3>Expertise</h3><p>Combining hardware, software, AI, and machine learning to contribute effectively and keep expanding what is possible.</p></article><article className="about-card"><div className="about-icon">🚀</div><h3>Approach</h3><p>Full-stack development with thoughtful interfaces, high-performance systems, and practical AI integration.</p></article></div></div></section>
    <section id="education" className="section"><div className="container"><h2 className="section-title">Education & Certifications</h2><div className="education-grid"><article className="education-item featured"><div className="education-icon">🎓</div><div><h3>Bachelor of Science in Computer Engineering</h3><p className="institution">Cebu Institute of Technology University</p><p className="dates">July 2021 - May 2025</p></div></article></div><h3 className="subsection-title">Certifications & Achievements</h3><div className="certifications-grid">{certifications.map(([icon, title, detail]) => <article className="cert-item" key={title}><div className="cert-icon">{icon}</div><h4>{title}</h4><p>{detail}</p></article>)}</div></div></section>
    <section id="contact" className="section alt-bg"><div className="container"><h2 className="section-title">Let's Work Together</h2><div className="contact-content"><p className="contact-intro">Have a product, workflow, or ambitious idea that needs a thoughtful technical partner?</p><div className="contact-grid"><ContactItem icon="📧" title="Email" value="aronetitong@gmail.com" href="https://mail.google.com/mail/?view=cm&fs=1&to=aronetitong@gmail.com" /><ContactItem icon="📱" title="Phone (PH)" value="+63 997 682 8086" href="tel:+639976828086" /><ContactItem icon="📍" title="Location" value="Cebu City, Philippines" /><ContactItem icon="💼" title="LinkedIn" value="Connect with me" href="https://www.linkedin.com/in/arone-christian-titong-2a12aa307" /><ContactItem icon="💻" title="GitHub" value="@datotakuboi" href="https://github.com/datotakuboi" /></div><div className="contact-cta"><a href="https://mail.google.com/mail/?view=cm&fs=1&to=aronetitong@gmail.com" target="_blank" rel="noreferrer" className="btn btn-primary btn-large"><span>Start a conversation</span><span aria-hidden="true">→</span></a></div></div></div></section>
    <footer className="footer"><div className="container"><div className="footer-content"><div className="footer-section"><h4>Arone Titong</h4><p>AI Software Developer · Building intelligent solutions</p></div><div className="footer-section"><h4>Explore</h4><ul><li><a href="#projects">Projects</a></li><li><a href="#experience">Experience</a></li><li><a href="#skills">Skills</a></li><li><a href="#contact">Contact</a></li></ul></div><div className="footer-section"><h4>Connect</h4><ul><li><a href="https://github.com/datotakuboi" target="_blank" rel="noreferrer">GitHub</a></li><li><a href="https://www.linkedin.com/in/arone-christian-titong-2a12aa307" target="_blank" rel="noreferrer">LinkedIn</a></li><li><a href="mailto:aronetitong@gmail.com">Email</a></li></ul></div></div><div className="footer-bottom"><p>© 2026 Arone Christian V. Titong. Crafted with care.</p></div></div></footer>
    <Chatbot />
  </PortfolioSkeleton>;
}

function ContactItem({ icon, title, value, href }) {
  return <article className="contact-item"><div className="contact-icon">{icon}</div><h3>{title}</h3>{href ? <a href={href} target={href.startsWith('http') ? '_blank' : undefined} rel={href.startsWith('http') ? 'noreferrer' : undefined}>{value}</a> : <p>{value}</p>}</article>;
}